version: "3.8"
services:
  web:
    container_name: "myportfolio"
    restart: "on-failure"
    build:
      context: ./
      dockerfile: Dockerfile
      # args:
      #   GITHUB_TOKEN: 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
      # target: runner
    env_file:
      - ./.env.local
    volumes:
      - "./next:/usr/src/next"
      - "/usr/src/next/node_modules"
      - "/usr/src/next/.next"

    ports:
      - "3003:3000"
